# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47ec863cd3959f3dcad9b3cd0e1499f85ccc5a666cf679653d71c8f36e217728cd906737e6e3b6f6f53d6c99605cc3326f1716d5985419d15f4450f8e7414119

test:
  secret_key_base: 2c60bea4ea9c46234f6f30790c2f245d35b84b5fa6ea0a52c8a5b4e6cc1005e0c486e57e3de5afc986ace42603c59ec0540d9a46f5048327f4b5b025c9cfe0fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
